package http

import (
	"fmt"
	"goserve/internal/config"
	"goserve/internal/service"
	"goserve/internal/transports/http/handler"
	"goserve/internal/transports/http/routes"

	swaggo "github.com/gofiber/contrib/v3/swaggo"
	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/fiber/v3/middleware/logger"
	"github.com/gofiber/fiber/v3/middleware/recover"

	// docs are generated by Swag CLI, you have to import them.
	// Replace with your own docs folder, usually "github.com/username/reponame/docs".
	_ "goserve/docs"
)

type Server struct {
	app      *fiber.App
	config   *config.Config
	handlers *handler.Handlers
}

// @title           Swagger Example API
// @version         1.0
// @description     This is a sample server celler server.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /api/v1

// @securityDefinitions.basic  BasicAuth

// @externalDocs.description  OpenAPI
// @externalDocs.url          https://swagger.io/resources/open-api/
func NewServer(config *config.Config, services *service.Services) *Server {
	logMiddleware := logger.New()
	app := fiber.New(fiber.Config{
		ErrorHandler: ErrorHandler(),
	})
	app.Use(recover.New(recover.Config{
		EnableStackTrace: true,
	}))
	app.Use(logMiddleware)
	// app.Use(translation.New())
	app.Use("/swagger/*", swaggo.HandlerDefault)
	// Customize the UI by passing a Config
	app.Get("/docs/*", swaggo.New(swaggo.Config{
		URL:          "http://example.com/doc.json",
		DeepLinking:  false,
		DocExpansion: "none",
		// TODO:
		// OAuth2RedirectUrl: "http://localhost:8080/swagger/oauth2-redirect.html",
	}))
	server := &Server{
		config:   config,
		app:      app,
		handlers: handler.New(services),
	}
	routes.Register(app.Group("/api/v1"), server.handlers)
	return server
}

func (s *Server) Start() error {
	return s.app.Listen(s.listenAddr())
}
func (s *Server) Shutdown() error {
	return s.app.Shutdown()
}

func (s *Server) listenAddr() string {
	return fmt.Sprintf("%s:%d", s.config.Http.Host, s.config.Http.Port)
}
